# Generated by Django 2.2.4 on 2020-04-28 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_institution', models.CharField(max_length=100)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(max_length=50)),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATS75.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TTCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=3)),
                ('time_slot_start', models.TimeField()),
                ('time_slot_end', models.TimeField()),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ATS75.Subject')),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATS75.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ARCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot_start', models.TimeField()),
                ('time_slot_end', models.TimeField()),
                ('value', models.CharField(max_length=2)),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATS75.Student')),
            ],
        ),
    ]
