# Generated by Django 2.2.4 on 2020-05-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS75', '0002_auto_20200429_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
