# Generated by Django 2.2.4 on 2020-05-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATS75', '0003_auto_20200503_2332'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arcell',
            unique_together={('user_ref', 'date', 'time_slot_start')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('user_ref', 'subject_code')},
        ),
        migrations.AlterUniqueTogether(
            name='ttcell',
            unique_together={('user_ref', 'day', 'time_slot_start')},
        ),
    ]
