# Generated by Django 2.2.4 on 2020-05-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS75', '0005_auto_20200504_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
